export const ARTICLES_IS_CHANGED = 'ARTICLES_IS_CHANGED';
export const ARTICLES_COUNT_IS_CHANGED = 'ARTICLES_COUNT_IS_CHANGED';
export const ARTICLES_LOADING_ERROR = 'ARTICLES_LOADING_ERROR';
export const ARTICLES_LOADING_START = 'ARTICLES_LOADING_START';
export const ARTICLES_LOADING_END = 'ARTICLES_LOADING_END';
export const PAGE_IS_CHANGED = 'PAGE_IS_CHANGED';

export const ARTICLE_PAGE_SHOW_DELETE_MODAL_WINDOW = 'ARTICLE_PAGE_SHOW_DELETE_MODAL_WINDOW';
export const ARTICLE_PAGE_HIDE_DELETE_MODAL_WINDOW = 'ARTICLE_PAGE_HIDE_DELETE_MODAL_WINDOW';
export const ARTICLE_PAGE_IS_CHANGED = 'ARTICLE_PAGE_IS_CHANGED';
export const ARTICLE_PAGE_LOADING_ERROR = 'ARTICLE_PAGE_LOADING_ERROR';
export const ARTICLE_PAGE_LOADING_START = 'ARTICLE_PAGE_LOADING_START';
export const ARTICLE_PAGE_LOADING_END = 'ARTICLE_PAGE_LOADING_END';

export const USERS_REGISTRATION_LOADING_ERROR = 'USERS_REGISTRATION_LOADING_ERROR';
export const USERS_REGISTRATION_LOADING_START = 'USERS_REGISTRATION_LOADING_START';
export const USERS_REGISTRATION_LOADING_END = 'USERS_REGISTRATION_LOADING_END';
export const USERS_REGISTRATION_ERRORS = 'USERS_REGISTRATION_ERRORS';

export const USERS_AUTHENTICATION_LOADING_ERROR = 'USERS_AUTHENTICATION_LOADING_ERROR';
export const USERS_AUTHENTICATION_LOADING_START = 'USERS_AUTHENTICATION_LOADING_START';
export const USERS_AUTHENTICATION_LOADING_END = 'USERS_AUTHENTICATION_LOADING_END';
export const USERS_AUTHENTICATION_ERRORS = 'USERS_AUTHENTICATION_ERRORS';

export const USER_IS_LOGGED = 'USER_IS_LOGGED';
export const LOGOUT = 'LOGOUT';

export const USERS_EDITING_LOADING_ERROR = 'USERS_EDITING_LOADING_ERROR';
export const USERS_EDITING_LOADING_START = 'USERS_EDITING_LOADING_START';
export const USERS_EDITING_LOADING_END = 'USERS_EDITING_LOADING_END';
export const USERS_EDITING_ERRORS = 'USERS_EDITING_ERRORS';
export const USERS_EDITING_SUCCESS = 'USERS_EDITING_SUCCESS';

export const CREATING_ARTICLE_LOADING_ERROR = 'CREATING_ARTICLE_LOADING_ERROR';
export const CREATING_ARTICLE_LOADING_START = 'CREATING_ARTICLE_LOADING_START';
export const CREATING_ARTICLE_LOADING_END = 'CREATING_ARTICLE_LOADING_END';
export const CREATING_ARTICLE_SUCCESS = 'CREATING_ARTICLE_SUCCESS';
export const CREATING_ARTICLE_DEFAULT_STATE = 'CREATING_ARTICLE_DEFAULT_STATE';

export const DELETING_ARTICLE_LOADING_ERROR = 'DELETING_ARTICLE_LOADING_ERROR';
export const DELETING_ARTICLE_LOADING_START = 'DELETING_ARTICLE_LOADING_START';
export const DELETING_ARTICLE_LOADING_END = 'DELETING_ARTICLE_LOADING_END';
export const DELETED_ARTICLE = 'DELETED_ARTICLE';

export const EDITING_ARTICLE_LOADING_ERROR = 'EDITING_ARTICLE_LOADING_ERROR';
export const EDITING_ARTICLE_LOADING_START = 'EDITING_ARTICLE_LOADING_START';
export const EDITING_ARTICLE_LOADING_END = 'EDITING_ARTICLE_LOADING_END';
export const EDITING_ARTICLE_SUCCESS = 'EDITING_ARTICLE_SUCCESS';
export const EDITING_ARTICLE_DEFAULT_STATE = 'EDITING_ARTICLE_DEFAULT_STATE';

export const CHANGED_TAGS_INFO_ON_CREATE_ARTICLE_PAGE = 'CHANGED_TAGS_INFO_ON_CREATE_ARTICLE_PAGE';
export const CHANGED_MAX_TAG_INDEX_ON_CREATE_ARTICLE_PAGE =
  'CHANGED_MAX_TAG_INDEX_ON_CREATE_ARTICLE_PAGE';

export const CHANGED_TAGS_INFO_ON_EDIT_ARTICLE_PAGE = 'CHANGED_TAGS_INFO_ON_EDIT_ARTICLE_PAGE';
export const CHANGED_MAX_TAG_INDEX_ON_EDIT_ARTICLE_PAGE =
  'CHANGED_MAX_TAG_INDEX_ON_EDIT_ARTICLE_PAGE';
